apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: maven-test-
spec:
  entrypoint: maven-test
  templates:
  - name: maven-test
    container:
      image: maven:3.9.9-eclipse-temurin-21-jammy
      command: [sh, -c]
      args: ["mvn clean test"]
      workingDir: /workspace
    volumes:
    - name: workspace
      emptyDir: {}
    inputs:
      artifacts:
      - name: source
        path: /workspace
        git:
          repo: https://github.com/forlixdev/test-karate-jenkins.git
    outputs:
      artifacts:
      - name: test-results
        path: /workspace/target/karate-reports
